use DarkServerUsers

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE SPECIFIC_NAME=N'CreateActiveLoginLession')
	DROP PROCEDURE CreateActiveLoginSession
GO

CREATE PROCEDURE CreateActiveLoginSession
	@USERACCOUNTID		INT,
	@LOGINDEVICEID		INT,
	@LOGINAPPID			INT,
	@SESSIONID			INT OUTPUT
AS
BEGIN
	IF (SELECT COUNT(*) FROM ActiveLoginSession WHERE UserAccountID=@USERACCOUNTID) > 0
	BEGIN
		IF (SELECT COUNT(*) FROM ActiveLoginSession WHERE LoginDeviceID=@LOGINDEVICEID) > 0
		BEGIN
			IF (SELECT COUNT(*) FROM ActiveLoginSession WHERE LoginAppID=@LOGINAPPID) > 0
			BEGIN
				SET @SESSIONID = -1;
			END
			ELSE
			BEGIN
				INSERT INTO ActiveLoginSession (UserAccountID, LoginDeviceID, LoginAppID) VALUES (@USERACCOUNTID, @LOGINDEVICEID, @LOGINAPPID)
				SET @SESSIONID = (SELECT ActiveLoginSessionID FROM ActiveLoginSession WHERE UserAccountID=@USERACCOUNTID AND LoginDeviceID=@LOGINDEVICEID AND LoginAppID=@LOGINAPPID);
			END
		END
	END
END
GO
